#!/bin/sh
#
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mkdir -p /tmp/android-data/dalvik-cache
CURR=`pwd`

ANDROID_PRINTF_LOG=tag \
ANDROID_LOG_TAGS="" \
ANDROID_DATA=/tmp/android-data \
ANDROID_ROOT=$CURR \
LD_LIBRARY_PATH=$CURR/lib \
exec $CURR/bin/dalvikvm \
-Xbootclasspath\
:$CURR/framework/core-hostdex.jar\
:$CURR/framework/bouncycastle-hostdex.jar\
:$CURR/framework/apache-xml-hostdex.jar \
-cp $1 $2

