all:
	ghdl -a hello.vhdl
	ghdl -e hello_world
	ghdl -r hello_world
	ghdl -a adder.vhdl
	ghdl -e adder
	ghdl -a adder_tb.vhdl
	ghdl -e adder_tb
	ghdl -r adder_tb
	ghdl -a test1.vhdl
	ghdl -e test1
	ghdl -r test1

clean:
	rm -f *.cf
